### ISSUE TITLE
Add the git tags to master branch and generate the release zip

### ISSUE THREAD

**Issue by Sefriol** [cralor/TourGuideClassic#14]
After #13 is merged, I need to push the git tags (one tag for original addon, second for v1.0.0-alpha) to master and generate release and change log.

**Comment by cralor** [comment]
Copy! Go for it!

**Comment by Sefriol** [comment]
https://github.com/cralor/TourGuideClassic/commit/d413f150e541a9bcd8c9f04a442a9eb3dab6237e
Is now the final commit for https://github.com/cralor/TourGuideClassic/releases/tag/v1.0.0-alpha

Had to force some updates since I messed some things up. Nothing major, but I didn't want to bloat commit history with trash.

I was able to update the release via script without manually having to do anything. Very cool!
